import Head from 'next/head'
import React from 'react';
import Router from 'next/router'
import { getCookie } from 'cookies-next';
import { Container } from '../components/CommonStyles'
import LoginForm from '../components/Login/Login'
import Footer from '../components/Footer'

export { getServerSideProps } from '../components/getDataFromCookies'

export default function Home({ data, setData, userData, setNotification }) {
  React.useEffect(() => {
    if (userData) setData(userData)
    if (getCookie('userCookie')) Router.push('/dashboard')
  }, [data, userData])

  return (
    <>
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
          <LoginForm setData={setData} setNotification={setNotification}/>
        </Container>
        <Footer />
    </>
  )
}
